<?php

namespace Zakarialabib\ConvertBootstrapToTailwind\Core;

class CompareClass
{
    /**
     * Map of Bootstrap class names to Tailwind class names.
     *
     * @var string[]
     */
    protected $classNameMap = [
        'alert' => 'rounded-md',
        'alert-primary' => 'bg-blue-500',
        'alert-secondary' => 'bg-gray-500',
        'alert-success' => 'bg-green-500',
        'alert-danger' => 'bg-red-500',
        'alert-warning' => 'bg-yellow-500',
        'alert-info' => 'bg-teal-500',
        'alert-light' => 'bg-gray-100',
        'alert-dark' => 'bg-gray-800',
        'align-baseline' => 'baseline',
        'align-top' => 'top',
        'align-middle' => 'middle',
        'align-bottom' => 'bottom',
        'align-text-top' => 'text-top',
        'align-text-bottom' => 'text-bottom',
        'align-items-start' => 'items-start',
        'align-items-end' => 'items-end',
        'align-items-center' => 'items-center',
        'align-items-baseline' => 'items-baseline',
        'align-items-stretch' => 'items-stretch',
        'align-content-start' => 'content-start',
        'align-content-end' => 'content-end',
        'align-content-center' => 'content-center',
        'align-content-between' => 'content-between',
        'align-content-around' => 'content-around',
        'align-content-stretch' => 'content-stretch',
        'align-self-auto' => 'self-auto',
        'align-self-start' => 'self-start',
        'align-self-end' => 'self-end',
        'align-self-center' => 'self-center',
        'align-self-stretch' => 'self-stretch',
        'badge' => 'inline-block px-2 py-1 rounded-full',
        'badge-pill' => 'rounded-full',
        'badge-primary' => 'bg-blue-500',
        'badge-secondary' => 'bg-gray-500',
        'badge-success' => 'bg-green-500',
        'badge-danger' => 'bg-red-500',
        'badge-warning' => 'bg-yellow-500',
        'badge-info' => 'bg-teal-500',
        'badge-light' => 'bg-gray-100',
        'badge-dark' => 'bg-gray-800',
        'bg-primary' => 'bg-blue-500',
        'bg-secondary' => 'bg-gray-500',
        'bg-success' => 'bg-green-500',
        'bg-danger' => 'bg-red-500',
        'bg-warning' => 'bg-yellow-500',
        'bg-info' => 'bg-teal-500',
        'bg-light' => 'bg-gray-100',
        'bg-dark' => 'bg-gray-800',
        'border-top' => 'border-t',
        'border-right' => 'border-r',
        'border-bottom' => 'border-b',
        'border-left' => 'border-l',
        'border-top-0' => 'border-t-0',
        'border-right-0' => 'border-r-0',
        'border-bottom-0' => 'border-b-0',
        'border-left-0' => 'border-l-0',
        'bottom' => 'bottom-0',
        'box-shadow' => 'shadow',
        'btn' => 'font-bold py-2 px-4 rounded',
        'btn-primary' => 'bg-blue-500 hover:bg-blue-700 text-white',
        'btn-secondary' => 'bg-gray-500 hover:bg-gray-700 text-white',
        'btn-success' => 'bg-green-500 hover:bg-green-700 text-white',
        'btn-danger' => 'bg-red-500 hover:bg-red-700 text-white',
        'btn-warning' => 'bg-yellow-500 hover:bg-yellow-700 text-white',
        'btn-info' => 'bg-indigo-500 hover:bg-indigo-700 text-white',
        'btn-light' => 'bg-gray-100 hover:bg-gray-700 text-white',
        'btn-dark' => 'bg-gray-800 hover:bg-gray-700 text-white',
        'btn-lg' => 'text-lg',
        'btn-sm' => 'text-sm',
        'btn-block' => 'block w-full',
        'card' => 'rounded-md',
        'card-header' => 'bg-gray-100',
        'card-header-tabs' => 'border-b-0',
        'card-header-pills' => 'border-radius-top-0',
        'card-body' => 'px-5 py-5',
        'card-title' => 'text-xl font-bold',
        'card-subtitle' => 'text-lg font-medium',
        'card-text' => 'text-base',
        'card-link' => 'text-blue-500',
        'card-footer' => 'bg-gray-100',
        'card-img-top' => 'rounded-t-md',
        'card-img-bottom' => 'rounded-b-md',
        'container' => 'max-w-5xl mx-auto',
        'container-fluid' => 'max-w-full',
        'col-auto' => 'flex-auto',
        'col' => 'w-full',
        'col-1' => 'w-1/12',
        'col-2' => 'w-2/12',
        'col-3' => 'w-3/12',
        'col-4' => 'w-4/12',
        'col-5' => 'w-5/12',
        'col-6' => 'w-6/12',
        'col-7' => 'w-7/12',
        'col-8' => 'w-8/12',
        'col-9' => 'w-9/12',
        'col-10' => 'w-10/12',
        'col-11' => 'w-11/12',
        'col-12' => 'w-full',
        'col-xs' => 'w-full',
        'col-sm' => 'sm:w-1/2',
        'col-md' => 'md:w-1/3',
        'col-lg' => 'lg:w-1/4',
        'col-xl' => 'xl:w-1/5',
        'custom-select' => 'appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500',
        'custom-file-input' => 'appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500',
        'clearfix' => 'clear-fix',
        'd-inline-block' => 'inline-block',
        'd-inline-flex' => 'inline-flex',
        'd-inline' => 'inline',
        'd-block' => 'block',
        'd-table' => 'table',
        'd-table-cell' => 'table-cell',
        'd-flex' => 'flex',
        'd-none' => 'hidden',
        'dropdown-item' => 'block w-full',
        'dropdown-menu' => 'z-50',
        'dropdown-toggle' => 'relative',
        'flex-row' => 'flex-row',
        'flex-row-reverse' => 'flex-row-reverse',
        'flex-column' => 'flex-col',
        'flex-column-reverse' => 'flex-col-reverse',
        'flex-wrap' => 'flex-wrap',
        'flex-nowrap' => 'flex-no-wrap',
        'flex-wrap-reverse' => 'flex-wrap-reverse',
        'flex-grow-0' => 'grow-0',
        'flex-grow-1' => 'grow',
        'flex-shrink-0' => 'shrink-0',
        'flex-shrink-1' => 'shrink',
        'font-weight-bold' => 'font-bold',
        'form-group' => 'my-6',
        'form-check' => 'items-center mx-2',
        'form-check-label' => 'mr-2',
        'form-check-inline' => 'inline-flex',
        'form-control' => 'appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500',
        'form-control-plaintext' => 'appearance-none block w-full bg-transparent text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500',
        'form-control-file' => 'appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500',
        'justify-content-start' => 'justify-start',
        'justify-content-end' => 'justify-end',
        'justify-content-center' => 'justify-center',
        'justify-content-between' => 'justify-between',
        'justify-content-around' => 'justify-around',
        'list-group' => 'divide-y divide-gray-200',
        'list-group-item' => 'px-5 py-3',
        'list-group-item-action' => 'cursor-pointer',
        'modal-dialog' => 'mx-auto',
        'modal-content' => 'rounded-md',
        'modal-header' => 'bg-gray-100',
        'modal-title' => 'text-2xl font-bold',
        'modal-body' => 'px-5 py-5',
        'modal-footer' => 'bg-gray-100',
        'nav-item' => 'inline-block',
        'nav-link' => 'text-blue-500',
        'navbar-brand' => 'text-xl',
        'navbar-toggler' => 'block',
        'navbar-toggler-icon' => 'w-8 h-8 fill-current',
        'offset-1' => 'ml-1/12',
        'offset-2' => 'ml-2/12',
        'offset-3' => 'ml-3/12',
        'offset-4' => 'ml-4/12',
        'offset-5' => 'ml-5/12',
        'offset-6' => 'ml-6/12',
        'offset-7' => 'ml-7/12',
        'offset-8' => 'ml-8/12',
        'offset-9' => 'ml-9/12',
        'offset-10' => 'ml-10/12',
        'offset-11' => 'ml-11/12',
        'order-first' => 'order-1',
        'order-last' => 'order-12',
        'row' => 'flex',
        'table' => 'table-auto',
        'thead-light' => 'text-gray-600',
        'tbody-light' => 'text-gray-700',
        'table-striped' => 'striped--light-gray',
        'table-bordered' => 'rounded',
        'table-hover' => 'hover:bg-gray-100',
        'table-sm' => 'text-xs',
        'table-active' => 'bg-gray-200',
        'table-light' => 'bg-gray-100',
        'table-dark' => 'bg-gray-800',
        'popover-title' => 'text-xl font-bold',
        'popover-content' => 'p-4',

    ];

    /**
     * Convert Bootstrap class names to Tailwind class names in an HTML string.
     *
     * @param  string  $html
     * @return string
     */
    public function compare(string $html)
    {
        // Extract all Bootstrap class names from the HTML
        preg_match_all('/\b(container|row|col-(?:xs|sm|md|lg|xl)|text-(?:left|center|right))\b/', $html, $matches);
        $bootstrapClassNames = $matches[0];

        // Replace each Bootstrap class name with its corresponding Tailwind class name
        foreach ($bootstrapClassNames as $className) {
            if (isset($this->classNameMap[$className])) {
                $html = str_replace($className, $this->classNameMap[$className], $html);
            }
        }

        return $html;
    }
}
